### ISSUE TITLE
key error when a url is used as the key and it's too long

### ISSUE THREAD

**Issue by MungoH** [iron-io/iron_cache_rails#10]
When libraries like Typhoeus create cache entries they can use long urls, this is sometimes failing for us. I've fixed it in a fork by using the encoded key when truncating it. In lib/active_support/cache/iron_cache.rb:70:

``` ruby
        if ekey.size > 250
          ekey = "#{key[0, 213]}:md5:#{Digest::MD5.hexdigest(key)}"
        end
```

becomes

``` ruby
        if ekey.size > 250
          ekey = "#{ekey[0, 213]}:md5:#{Digest::MD5.hexdigest(ekey)}"
        end
```

**Comment by treeder** [comment]
Can you give us a pull request?
